Datatable activity
strandls/biodiv-activity pull request #51
Opened 2021-08-02 15:42 UTC by teamdraftbox

Datatable activity logger added to activity module

2021-08-11 12:19 UTC, akrudra requested changes

2021-08-11 12:19 UTC, akrudra commented on src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java
> +//	DOCUMENT ACTIVITY LIST
Data table activity list

2021-08-11 12:19 UTC, akrudra commented on src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java
> +		} else if (dataTableNullActivityList.contains(loggingData.getActivityType())) {
Inside observation logging why data table is being logged ??

2021-08-11 12:19 UTC, akrudra commented on src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java
> +				activity = new Activity(null, 0L, loggingData.getActivityDescription(), loggingData.getActivityId(),
activity holder type should be comment, in case of comment activities

2021-08-11 12:19 UTC, akrudra commented on src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java
> +				activity = activityDao.save(activity);
return the activity

2021-08-11 12:19 UTC, akrudra commented on src/main/java/com/strandls/activity/ActivityEnums.java
> +	DATATABLE("content.eml.Datatable"),USERGROUP("species.groups.UserGroup"), FACTS("species.trait.Fact"),DATATABLECOMMENT("content.eml.Datatable.Comment"), COMMENTS("species.participation.Comment"),
data table comment is used where ??

2021-08-13 07:36 UTC, teamdraftbox commented on src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java
> +				activity = new Activity(null, 0L, loggingData.getActivityDescription(), loggingData.getActivityId(),
https://github.com/strandls/biodiv-activity/blob/datatable-activity/src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java#L639

2021-08-13 07:37 UTC, teamdraftbox commented on src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java
> +				activity = activityDao.save(activity);
https://github.com/strandls/biodiv-activity/blob/datatable-activity/src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java#L651

2021-08-13 08:19 UTC, akrudra requested changes
Please resolve the comment, it's a defect.
Format the code and remove unnecessary comments, if any

2021-08-13 08:19 UTC, akrudra commented on src/main/java/com/strandls/activity/service/impl/ActivityServiceImpl.java
> +				activity = new Activity(null, 0L, loggingData.getActivityDescription(), loggingData.getActivityId(),
please resolve the activity holder type, rest looks fine

2021-08-13 15:13 UTC, merged